// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ID          int64
	ShortCode   string
	OriginalUrl string
	Clicks      int64
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	UserID      pgtype.Int8
}

type User struct {
	ID             int64
	Name           string
	Email          string
	HashedPassword string
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}
