// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: urls.sql

package database

import (
	"context"
)

const addURL = `-- name: AddURL :one
INSERT INTO
    urls (short_code, original_url)
VALUES
    ($1, $2)
RETURNING
    id, short_code, original_url, clicks, created_at, updated_at, user_id
`

type AddURLParams struct {
	ShortCode   string
	OriginalUrl string
}

func (q *Queries) AddURL(ctx context.Context, arg AddURLParams) (Url, error) {
	row := q.db.QueryRow(ctx, addURL, arg.ShortCode, arg.OriginalUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.Clicks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteURL = `-- name: DeleteURL :exec
DELETE FROM urls
WHERE
    short_code = $1
`

func (q *Queries) DeleteURL(ctx context.Context, shortCode string) error {
	_, err := q.db.Exec(ctx, deleteURL, shortCode)
	return err
}

const getLongURL = `-- name: GetLongURL :one
SELECT
    original_url
FROM
    urls
WHERE
    short_code = $1
`

func (q *Queries) GetLongURL(ctx context.Context, shortCode string) (string, error) {
	row := q.db.QueryRow(ctx, getLongURL, shortCode)
	var original_url string
	err := row.Scan(&original_url)
	return original_url, err
}

const getURLByLongURL = `-- name: GetURLByLongURL :one
SELECT
    id, short_code, original_url, clicks, created_at, updated_at, user_id
FROM
    urls
WHERE
    original_url = $1
LIMIT
    1
`

func (q *Queries) GetURLByLongURL(ctx context.Context, originalUrl string) (Url, error) {
	row := q.db.QueryRow(ctx, getURLByLongURL, originalUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.Clicks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const incrementClicks = `-- name: IncrementClicks :exec
UPDATE urls
SET
    clicks = clicks + 1
WHERE
    short_code = $1
`

func (q *Queries) IncrementClicks(ctx context.Context, shortCode string) error {
	_, err := q.db.Exec(ctx, incrementClicks, shortCode)
	return err
}

const updateURL = `-- name: UpdateURL :one
UPDATE urls
SET
    original_url = $2,
    updated_at = NOW()
WHERE
    short_code = $1
RETURNING
    id, short_code, original_url, clicks, created_at, updated_at, user_id
`

type UpdateURLParams struct {
	ShortCode   string
	OriginalUrl string
}

func (q *Queries) UpdateURL(ctx context.Context, arg UpdateURLParams) (Url, error) {
	row := q.db.QueryRow(ctx, updateURL, arg.ShortCode, arg.OriginalUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.Clicks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
